<?php
<?php
/**
 * Database Connection Class (detailed teaching comments)
 *
 * This class demonstrates a simple Singleton wrapper around mysqli. Key PHP
 * concepts shown here: classes, visibility (public/private), static properties,
 * constructors, try/catch exceptions, and object destruction.
 */
class Database {
    // static property holds the single instance shared across the application
    private static $instance = null;
    // $connection stores the mysqli object once we connect
    private $connection;

    // Hard-coded defaults (for teaching/demo). In real apps use env vars or a config loader.
    private $host = "sql113.infinityfree.com"; // host string
    private $username = "if0_40185804"; // DB username
    private $password = "careerhub12"; // DB password (unsafe to commit in real projects)
    private $database = "if0_40185804_uniconnect_db"; // DB name

    /**
     * Private constructor prevents creating the object directly with `new Database()`.
     * Use Database::getInstance() instead to enforce a single connection.
     */
    private function __construct() {
        // Make mysqli throw exceptions to simplify error handling (see includes/db.php for alternative patterns)
        mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);

        try {
            // Create the mysqli connection object. This can throw mysqli_sql_exception.
            $this->connection = new mysqli(
                $this->host,
                $this->username,
                $this->password,
                $this->database
            );

            // Set character set to utf8mb4 for full Unicode support (emojis, etc.)
            $this->connection->set_charset("utf8mb4");
        } catch (mysqli_sql_exception $e) {
            // Log the detailed DB error for administrators, but throw a generic exception to callers.
            error_log("Database Connection Error: " . $e->getMessage());
            throw new Exception("Database connection failed. Please try again later.");
        }
    }

    /**
     * getInstance
     * - Returns the single Database instance, creating it the first time it's called.
     * - `self::` is used to access static properties/methods from within the class.
     */
    public static function getInstance() {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    /**
     * getConnection
     * - Return the underlying mysqli object so models can execute queries.
     */
    public function getConnection() {
        return $this->connection;
    }

    /**
     * escape
     * - A convenience wrapper around mysqli::real_escape_string. Teaching note:
     *   prefer prepared statements instead of manual escaping when inserting values
     *   into SQL. Escaping is useful for legacy dynamic SQL.
     */
    public function escape($value) {
        return $this->connection->real_escape_string($value);
    }

    /**
     * lastInsertId
     * - Return the last auto-increment ID generated by the current connection.
     */
    public function lastInsertId() {
        return $this->connection->insert_id;
    }

    /**
     * close
     * - Close the underlying mysqli connection if it exists.
     */
    public function close() {
        if ($this->connection) {
            $this->connection->close();
        }
    }

    /**
     * Prevent cloning of the singleton instance.
     */
    private function __clone() {}

    /**
     * Prevent unserialization of the singleton instance.
     */
    public function __wakeup() {
        throw new Exception("Cannot unserialize singleton");
    }

    /**
     * __destruct
     * - PHP calls this automatically when the object is garbage-collected. We
     *   close the DB connection here as a safety net.
     */
    public function __destruct() {
        $this->close();
    }
}
